### PR TITLE
Included everything except actually saving a record in a dry run

### PR DESCRIPTION
**Pull request by boblail**
I don't know if this is a good idea or not.

Before, if you specified `--dry-run`, it would skip creating each record and also all the callbacks around record-creation.

Now, if you specify `--dry-run`, it will do everything (even faking the ID map) including callbacks, except actually saving the record.

I like:
- that this exercises more of the code in a dry run
- particularly that it gets you to test validations

I dislike:
- that callbacks like `after_create` will be called without a real, persisted record (those callbacks might make defendable assumptions that the record exists!)

### CODE REVIEW

**Comment by ben5516** [comment]
This seems unsafe. Like you said, callbacks might fairly make assumptions that the record has actually been saved. Also, this doesn't prevent callbacks for saving to the DB themselves, which could create wrong/orphan data.

**Comment by ben5516** [comment]
I think it'd make more since to only run the `before_save` callbacks on a dry run.

**Comment by boblail** [comment]
@ben5516 maybe same thing, but don't call
```
invoke_callback(:after_create, hash, record)
invoke_callback(:after_save, hash, record)
```
?

I do like the ability to see validation fails...

**Comment by ben5516** [comment]
:+1: on that idea @boblail

**Comment by kobsy** [comment]
A fine idea, but after 5 years of inaction, I'm going to go ahead and close this one.

**Pull request closed without merging**
